### ISSUE TITLE
Social Profile(eg Twitter, Linkedin) Integration

### ISSUE THREAD

**Issue by ayushgarg1804** [IpshitaC/sociable#1]
There should be a feature analyzing a person using their profile from twitter.

**Comment by prachi1210** [comment]
@ayushgarg1804 Given that the software requires atleast 6000 words for reasonable analysis and the microblogging platform uses just 140 characters. Don't you think this might be unrealistic?

**Comment by ayushgarg1804** [comment]
@prachi1210 Didnt mean it to just analyse on a single tweet. Maybe it can analyse on some (100s or so :P) latest tweets from someone's profile?

**Comment by prachi1210** [comment]
Don't you think that would be too random and would confuse the algorithm as it would include retweets and even shorthand ( we don't always tweet using proper English)? And even with 100s of tweets, I think the data may not be sufficient. 6000 words is no mean feat.

**Comment by ayushgarg1804** [comment]
Yeah I know it was just a suggestion. And also I think its great for experimentation and maybe the result might just be interesting.

**Comment by prachi1210** [comment]
In my opinion, something like a Linkedin summary/personal blog/portfolio may be a better candidate. You may want to rename your issue. 👍

**Comment by ayushgarg1804** [comment]
Social profile then.

**Comment by IpshitaC** [comment]
On a slightly different note, is it actually ethical for employers to monitor or analyze any social media account of applicants, since in most cases they do not voluntarily submit their social media profiles (such as Twitter) for scrutiny? This point is all the more pertinent since the applicant is not employed by the firm at the application stage and consequently not bound by the company regulations.

**Comment by IpshitaC** [comment]
I agree with @prachi1210 about analyzing Twitter feeds of applicants, which may lead to erroneous results.
